version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../data:/app/data:ro
    environment:
      - DATABASE_PATH=/app/data/climatetrade.db
    networks:
      - climatetrade

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - climatetrade

networks:
  climatetrade:
    driver: bridge